### ISSUE TITLE
parse GPX file throw a exception

### ISSUE THREAD

**Issue by yhonet** [himanshu-soni/gpx-parser#2]
I don't know what data cause this exception, maybe like "&lt;ele/&gt;".

There is a same problem in another lib:
https://github.com/ticofab/android-gpx-parser
I post a issue at:
https://github.com/ticofab/android-gpx-parser/issues/1

Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.w3c.dom.Node.getNodeValue()' on a null object reference
                                                                               at com.hs.gpxparser.GPXParser.getNodeValueAsDouble(GPXParser.java:515)
                                                                               at com.hs.gpxparser.GPXParser.parseWaypoint(GPXParser.java:331)
                                                                               at com.hs.gpxparser.GPXParser.parseTrackSegment(GPXParser.java:488)
                                                                               at com.hs.gpxparser.GPXParser.parseTrack(GPXParser.java:466)
                                                                               at com.hs.gpxparser.GPXParser.parseGPX(GPXParser.java:98)

**Comment by ThomasDaheim** [comment]
I have checked <ele/> and that gives a proper parser exception:

org.xml.sax.SAXParseException; lineNumber: 14; columnNumber: 6; The element type "ele" must be terminated by the matching end-tag "</ele>".

Impossible to say without an example file
